---
title: Lineplots
author: Jens Hooge
date: '2017-07-12'
thumbnail: "images/ribbon.png"
slug: lineplots
categories:
  - general
tags:
  - exploration
draft: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

## Generate Data
```{r dataset, tidy=FALSE, , warning=FALSE}
library(BioViz)
library(reshape2)
library(ggplot2)
n=7
df <- data.frame(Dose1=exp((1/2)*1:n),
                 Dose2=exp((1/3)*1:n),
                 Dose3=exp((1/4)*1:n),
                 Dose4=exp((1/5)*1:n),
                 Dose5=exp((1/6)*1:n),
                 Dose6=exp((1/7)*1:n),
                 Visit=1:n)
df <- melt(df, id=c("Visit"))
colnames(df) <- c("Visit", "Dose", "Measure") 
```

## Lineplot with Errorbars
```{r errorbars, tidy=FALSE}
general.lineplot(df, upper.err=1, lower.err=1, var.type="errorbar")
```

## Lineplot with Errorbars and log transformed y-axis
```{r error_transform, tidy=FALSE}
general.lineplot(df, upper.err=1, lower.err=1, var.type="errorbar", y.log10trans = T)
```

## Facetted Lineplot
```{r facetted, tidy=FALSE}
general.lineplot(df, by="Dose", facet.row=3, upper.err=1, lower.err=1,
                 var.type="errorbar", y.log10trans = T)
```

## Lineplot with Error Ribbons
```{r ribbon, tidy=FALSE}
general.lineplot(df, by="Dose", upper.err=1, lower.err=1, var.type="ribbon")
```

## Lineplot with Error Ribbon and log transformed y-axis
```{r ribbon_transform, tidy=FALSE}
general.lineplot(df, by="Dose", upper.err=1, lower.err=1, var.type="ribbon", y.log10trans = T)
```
